// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo2_kASRlJrinnmnEPAAr6bKx1TsDeNJ4',
    appId: '1:582627579405:web:c9a3a08d71243aaacfe744',
    messagingSenderId: '582627579405',
    projectId: 'meals-72a26',
    authDomain: 'meals-72a26.firebaseapp.com',
    storageBucket: 'meals-72a26.appspot.com',
    measurementId: 'G-5NCQCB9Q3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu3nO4SmCKUbADfFKGp5_FJ-bLWHBqc6M',
    appId: '1:582627579405:android:edbaccbeb554360dcfe744',
    messagingSenderId: '582627579405',
    projectId: 'meals-72a26',
    storageBucket: 'meals-72a26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ7mnBERjASn87W6ebOFCN3SjuG6YM4Dc',
    appId: '1:582627579405:ios:fa289b56fbdb954ecfe744',
    messagingSenderId: '582627579405',
    projectId: 'meals-72a26',
    storageBucket: 'meals-72a26.appspot.com',
    iosBundleId: 'com.example.meals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ7mnBERjASn87W6ebOFCN3SjuG6YM4Dc',
    appId: '1:582627579405:ios:fa289b56fbdb954ecfe744',
    messagingSenderId: '582627579405',
    projectId: 'meals-72a26',
    storageBucket: 'meals-72a26.appspot.com',
    iosBundleId: 'com.example.meals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo2_kASRlJrinnmnEPAAr6bKx1TsDeNJ4',
    appId: '1:582627579405:web:20c14d188d9d018ecfe744',
    messagingSenderId: '582627579405',
    projectId: 'meals-72a26',
    authDomain: 'meals-72a26.firebaseapp.com',
    storageBucket: 'meals-72a26.appspot.com',
    measurementId: 'G-DQ6RF35XVL',
  );
}
